### ISSUE TITLE
Is it possible to use this library in nodejs?

### ISSUE THREAD

**Issue by codingmaven** [StephanGeorg/leaflet-routeboxer#9]

**Comment by StephanGeorg** [comment]
I never tried because it is a leaflet plugin and leaflet in general is designed for the browser. So you need to use [leaflet-headless](https://github.com/jieter/leaflet-headless) with node, it uses jsdom to fake the DOM. Would be nice to hear if this actually works.

If you do not need leaflet you can use [geojson.lib.routeboxer](https://www.npmjs.com/package/geojson.lib.routeboxer) instead.
